"""Do paper.md and the built paper.pdf carry the same prose?

paper.md and paper.tex are two hand-maintained masters; paper.pdf is compiled
from the tex, so it stands in for it. Edits are applied to both files by hand,
and when the two wrap a sentence differently a paired edit can land in one file
only. That happened repeatedly, and once left a claim in the PDF that the
markdown had already retracted.

check_numbers.py guards the NUMBERS in paper.md. This guards the PROSE across
the pair, in BOTH directions:

  md -> pdf   prose written in the markdown that never reached the tex
  pdf -> md   prose in the artifact that the markdown does not have

Both sides are reduced to sequences of significant word-stems before matching,
so line wrapping, hyphenation and punctuation differences do not matter. Only
content does.

  python check_sync.py            # report
  python check_sync.py --quiet    # exit code only (0 = in sync)

Known-benign reports are listed in ACCEPTED below with the reason. Anything not
listed is a real divergence until shown otherwise.
"""
import re
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

P = Path(__file__).resolve().parent
QUIET = "--quiet" in sys.argv

# Sentences whose absence is a rendering artefact, not a divergence. Each is
# matched by a distinctive substring and carries the reason it is exempt.
ACCEPTED = [
    # Each verified by hand against the built PDF: the CONTENT is present, only
    # the surface form differs. Anything not listed here is a real divergence.
    ("citation key in brackets resolves",
     "front-matter line; set as an unnumbered italic block in the tex"),
    ("masks obtainable by in-budget perturbation",
     "paper.md gives Proposition 1 a prose lead-in; the tex states it as a bare "
     "theorem display. Same proposition, deliberately different presentation"),
    ("persistence rank lower-bounds",
     "md says 'for every reachable mask M', tex 'for every reachable M'; the "
     "whole paragraph was diffed and is otherwise identical"),
    ("Nothing about the input", "arrow glyph plus code spans; verified present"),
    ("upward-monotone conjunct", "Lemma 1 proof; verified present by direct grep"),
    ("varying numerators at",
     "Table 2 caption is generated by tables.py; wording differs, every number "
     "verified against the committed JSON"),
    ("toy-track sweep", "Table 3 caption comes from generated/table_toy.tex"),
    ("certifies the input", "arrow glyph; verified present (2 occurrences)"),
    ("in both; only the second survives", "math-dense appendix sentence"),
]


# paper.md carries ABBREVIATED figure captions and no table bodies by design,
# so the PDF legitimately holds prose the markdown does not. These are the
# verified categories; anything outside them is a real divergence.
ACCEPTED_PDF_ONLY = [
    ("Read off the exactly-nested sweep", "hero caption; md's is abbreviated"),
    ("A frozen segmenter produces the score map", "pipeline figure caption"),
    ("Given any M with", "Proposition 1 proof, math-dense"),
    ("Coverage (certainly-fg fraction", "Table 1 body"),
    ("Certified 0 components", "Table 1 body"),
    ("Certified enclosed tesserae", "Table 1 body"),
    ("connected grout fraction", "Table 1 body"),
    ("Certified 1-cycles, two ways", "Table 1 body"),
    ("Confident tiles are certified", "gallery caption"),
    ("One tile's interior is set model-uncertain", "gallery caption"),
    ("upward-monotone conjunct", "Lemma 1 proof, math-dense"),
    ("eps coverage conn-len", "table body"),
    ("Same three series", "sweep-figure caption"),
    ("Toy p is a blurred copy", "Table 3 caption from tables.py"),
    ("each certified quantity across DRIVE", "decoupling-figure caption"),
    ("the largest budget at which it provably", "hero caption"),
    ("budgets are graded", "hero caption"),
    ("per-pixel margin", "hero caption"),
    ("what INTACT actually certifies", "hero caption"),
    ("image crop score map", "pipeline figure, extracted as glyph soup"),
    ("Preprint v1", "title block"),
    ("localises at exactly one extreme", "tightness-figure caption mirrors the body"),
    ("frozen-model score map", "anatomy-figure caption"),
    ("the same gap collapses", "sweep-figure caption"),
    ("fundus green channel", "vessel-montage caption"),
    ("thin joints erode", "gallery caption"),
    ("A CERT_FG ring over a POSSIBLE interior", "counterexample-figure caption"),
    ("abstention floods", "anatomy-figure caption"),
    ("Per-crop distribution of coverage", "Appendix A figure caption"),
    ("Read the two clouds", "decoupling-figure caption"),
    ("certifies the inputmap pipeline",
     "arrow glyph lost by pdftotext; the sentence is present in paper.md"),
    ("The worst crop (min", "Appendix A figure caption"),
    ("Paetzold", "bibliography author list"),
    ("On the effectiveness of interval bound propagation", "bibliography title"),
    ("Abstract interpretation: A unified lattice model", "bibliography title"),
    ("GROUT: Geometric reasoning over unstructured", "bibliography title"),
]


def norm(t):
    return " ".join(re.sub(r"[^a-z0-9]+", " ", t.lower()).split())


def sig(t):
    """Both sides MUST go through this. Filtering one side only was the bug in
    the first version of this check; it reported 91 false divergences."""
    return [w for w in norm(t).split() if w.isalpha() and len(w) > 2]


def sentences(text):
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]


def present(words, haystack):
    """Present if any 6-gram of the sentence occurs in the haystack."""
    if len(words) < 10:
        return True                     # too short to fingerprint reliably
    for i in range(0, max(1, len(words) - 6), 3):
        if " ".join(words[i:i + 6]) in haystack:
            return True
    return False


def accepted(s, table=None):
    """Whitespace-collapsed comparison. Matching the raw text failed silently,
    because paper.md wraps sentences and the fragments here do not."""
    flat = " ".join(s.split()).lower()
    for frag, why in (table if table is not None else ACCEPTED):
        if " ".join(frag.split()).lower() in flat:
            return why
    return None


# ------------------------------------------------------------------ sources
pdf_raw = subprocess.run(["pdftotext", str(P / "paper.pdf"), "-"],
                         capture_output=True).stdout.decode("utf-8", "replace")
pdf_raw = pdf_raw.replace("-\n", "")               # de-hyphenate
PDF = " ".join(sig(pdf_raw))

md_raw = (P / "paper.md").read_text(encoding="utf-8")
md_raw = re.sub(r"```.*?```", " ", md_raw, flags=re.S)      # code fences
md_raw = re.sub(r"^\|.*$", " ", md_raw, flags=re.M)         # tables
md_raw = re.sub(r"^#+.*$", " ", md_raw, flags=re.M)         # headings
md_raw = re.sub(r"\*\(.*?\)\*", " ", md_raw, flags=re.S)    # caption asides
md_raw = re.sub(r"`[^`]*`", " X ", md_raw)                  # code spans
md_raw = re.sub(r"\[[^\]]*\]", " ", md_raw)                 # citation keys
md_raw = md_raw.replace("*", " ").replace("—", " ").replace("–", " ")
MD = " ".join(sig(md_raw))

# ------------------------------------------------------- md -> pdf direction
md_missing, md_excused = [], 0
for s in sentences(md_raw):
    if not present(sig(s), PDF):
        if accepted(s):
            md_excused += 1
        else:
            md_missing.append(s)

# ------------------------------------------------------- pdf -> md direction
# The PDF carries material the markdown legitimately lacks: the bibliography,
# table bodies, figure captions and running heads. Skip those.
# paper.md carries ABBREVIATED figure captions by design and no table bodies,
# so the PDF legitimately contains prose the markdown does not. Skip captions,
# table rows, headings and the bibliography; what survives is body prose.
SKIP = re.compile(
    r"^\s*(\[\d+\]|Figure~?\s*\d|Table~?\s*\d|\d+(\.\d+)*\s|\(?[a-e]\))"
    r"|doi:|arXiv|proceedings|"
    r"^\s*[\d.]+\s+[\d.]+\s|"
    r"\b(Left|Right|Middle|Top|Bottom|Per row|Dashed outline|box =|whiskers =)\s*:?"
    # Bibliography: paper.md carries one-line glosses, the PDF full records.
    r"|\b(In Proceedings|In Conference|In Medical Image|volume \d|pages \d|LNCS"
    r"|References|Springer|IEEE|PMLR|NeurIPS|ICML|ICLR)\b",
    re.I)
pdf_missing = []
for s in sentences(pdf_raw):
    if SKIP.search(s) or len(s) < 60:
        continue
    if not present(sig(s), MD) and not accepted(s, ACCEPTED_PDF_ONLY):
        pdf_missing.append(s)

# ------------------------------------------------------------------ report
if not QUIET:
    print(f"md -> pdf : {len(md_missing)} unexplained "
          f"({md_excused} known rendering artefacts excused)")
    print(f"pdf -> md : {len(pdf_missing)} unexplained")
    print()
    for tag, items in (("IN paper.md BUT NOT IN THE BUILT PDF", md_missing),
                       ("IN THE BUILT PDF BUT NOT IN paper.md", pdf_missing)):
        if items:
            print(f"### {tag}")
            for m in items:
                print(f"  - {' '.join(m.split())[:200]}")
            print()
    if not md_missing and not pdf_missing:
        print("IN SYNC: every fingerprinted sentence appears on both sides.")

sys.exit(1 if (md_missing or pdf_missing) else 0)
